# DigitalOcean App Platform Configuration
name: hazirgiyim-backend
region: fra
services:
- name: web
  github:
    repo: hazirgiyimkaliplari2-rgb/hazirgiyim-backend
    branch: main
    deploy_on_push: true
  build_command: npm ci && npm run build:prod
  run_command: npm run start:prod
  http_port: 9000
  instance_size_slug: professional-xs
  instance_count: 1
  health_check:
    http_path: /health
    initial_delay_seconds: 30
    period_seconds: 30
    timeout_seconds: 5
    success_threshold: 1
    failure_threshold: 3
  routes:
    - path: /
  envs:
  - key: NODE_ENV
    scope: RUN_AND_BUILD_TIME
    value: production
  - key: DATABASE_URL
    scope: RUN_TIME
    value: ${db.DATABASE_URL}
  - key: REDIS_URL
    scope: RUN_TIME
    value: ${redis.REDIS_URL}
  - key: JWT_SECRET
    scope: RUN_TIME
    type: SECRET
  - key: COOKIE_SECRET
    scope: RUN_TIME
    type: SECRET
  - key: STRIPE_API_KEY
    scope: RUN_TIME
    type: SECRET
  - key: STRIPE_WEBHOOK_SECRET
    scope: RUN_TIME
    type: SECRET
  - key: RESEND_API_KEY
    scope: RUN_TIME
    type: SECRET
  - key: GROQ_API_KEY
    scope: RUN_TIME
    type: SECRET

databases:
- name: db
  engine: PG
  version: "15"
  size: professional-xs
  num_nodes: 1
  production: true

# Redis can be added via DigitalOcean Managed Redis
# or use an external Redis service