services:
  - type: web
    name: hazirgiyim-admin-panel
    runtime: node
    region: frankfurt
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm run start:prod
    healthCheckPath: /health
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://postgres:mlwPULVjheuUhbAGixInHBeiiHjVhMDh@yamabiko.proxy.rlwy.net:28022/railway
      - key: DATABASE_PUBLIC_URL
        value: postgresql://postgres:mlwPULVjheuUhbAGixInHBeiiHjVhMDh@yamabiko.proxy.rlwy.net:28022/railway
      - key: JWT_SECRET
        value: 7U/GHYUboEFqlicugpQ0pLhLkzpk+LVncghPxK1Loog=
      - key: COOKIE_SECRET
        value: Snyo90LRQdWI25egm6bXNOybfEGMnVhDDSnddd4De2mM=
      - key: STORE_CORS
        value: "*"
      - key: ADMIN_CORS
        value: "*"
      - key: AUTH_CORS
        value: "*"
    autoDeploy: true